[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "loom-demo"
version = "0.1.0"
description = "Minimal Loom-like async task tracer demo"
authors = [{name = "Generated", email = "you@example.com"}]
requires-python = ">=3.8"
